### ISSUE TITLE
Headers underline not working

### ISSUE THREAD

**Issue by mingganglee** [krios2146/obsidian-github#30]
# Headers underline not working

## Env

- Mac x86
- Obsidian Version: v1.7.7

## Fix

```css
/* Underline for the top level headers */

body.h1-underline h1, body.h1-underline.markdown-rendered h1 {
    padding-bottom: .3em;
    border-bottom: 1px solid var(--color-base-40);
}
body.h2-underline h2, body.h2-underline.markdown-rendered h2 {
    padding-bottom: .3em;
    border-bottom: 1px solid var(--color-base-40);
}

/* Add H1, H2 css and start working */

h1, h2 {
    padding-bottom: .3em;
    border-bottom: 1px solid #dfe2e5;
}
```
